//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.07 at 12:28:08 PM BST 
//


package com.maidenhotels.Backend.tibco.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/TIBCO/Maiden_Hotels_Project/Schemas/Clients.xsd}GuestClient" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id_guest" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="money_spent" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guestClient"
})
@XmlRootElement(name = "Client", namespace = "http://www.tibco.com/schemas/TIBCO/Maiden_Hotels_Project/Schemas/Clients.xsd")
public class Client {

    @XmlElement(name = "GuestClient", namespace = "http://www.tibco.com/schemas/TIBCO/Maiden_Hotels_Project/Schemas/Clients.xsd")
    protected List<GuestClient> guestClient;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "id_guest")
    protected String idGuest;
    @XmlAttribute(name = "money_spent")
    protected String moneySpent;
    @XmlAttribute(name = "password")
    protected String password;

    public Client() {
    }

    public Client(List<GuestClient> guestClient, String id, String idGuest, String moneySpent, String password) {
        this.guestClient = guestClient;
        this.id = id;
        this.idGuest = idGuest;
        this.moneySpent = moneySpent;
        this.password = password;
    }

    /**
     * Gets the value of the guestClient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the guestClient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGuestClient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GuestClient }
     * 
     * 
     */
    public List<GuestClient> getGuestClient() {
        if (guestClient == null) {
            guestClient = new ArrayList<GuestClient>();
        }
        return this.guestClient;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idGuest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdGuest() {
        return idGuest;
    }

    /**
     * Sets the value of the idGuest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdGuest(String value) {
        this.idGuest = value;
    }

    /**
     * Gets the value of the moneySpent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoneySpent() {
        return moneySpent;
    }

    /**
     * Sets the value of the moneySpent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoneySpent(String value) {
        this.moneySpent = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

}
