//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.07 at 12:28:08 PM BST 
//


package com.maidenhotels.Backend.tibco.schemas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.maidenhotels.Backend.tibco.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.maidenhotels.Backend.tibco.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Backoffice }
     * 
     */
    public Backoffice createBackoffice() {
        return new Backoffice();
    }

    /**
     * Create an instance of {@link Backoffices }
     * 
     */
    public Backoffices createBackoffices() {
        return new Backoffices();
    }

    /**
     * Create an instance of {@link StatusBackoffice }
     * 
     */
    public StatusBackoffice createStatusBackoffice() {
        return new StatusBackoffice();
    }

    /**
     * Create an instance of {@link SuccessBackoffice }
     * 
     */
    public SuccessBackoffice createSuccessBackoffice() {
        return new SuccessBackoffice();
    }

    /**
     * Create an instance of {@link BkGuests }
     * 
     */
    public BkGuests createBkGuests() {
        return new BkGuests();
    }

    /**
     * Create an instance of {@link BkServices }
     * 
     */
    public BkServices createBkServices() {
        return new BkServices();
    }

    /**
     * Create an instance of {@link BkroomsHotel }
     * 
     */
    public BkroomsHotel createBkroomsHotel() {
        return new BkroomsHotel();
    }

    /**
     * Create an instance of {@link Booking }
     * 
     */
    public Booking createBooking() {
        return new Booking();
    }

    /**
     * Create an instance of {@link BookingGuest }
     * 
     */
    public BookingGuest createBookingGuest() {
        return new BookingGuest();
    }

    /**
     * Create an instance of {@link Bookings }
     * 
     */
    public Bookings createBookings() {
        return new Bookings();
    }

    /**
     * Create an instance of {@link BookingsGuests }
     * 
     */
    public BookingsGuests createBookingsGuests() {
        return new BookingsGuests();
    }

    /**
     * Create an instance of {@link BookingsRoomsHotel }
     * 
     */
    public BookingsRoomsHotel createBookingsRoomsHotel() {
        return new BookingsRoomsHotel();
    }

    /**
     * Create an instance of {@link BookingsRoomsHotels }
     * 
     */
    public BookingsRoomsHotels createBookingsRoomsHotels() {
        return new BookingsRoomsHotels();
    }

    /**
     * Create an instance of {@link BookingsService }
     * 
     */
    public BookingsService createBookingsService() {
        return new BookingsService();
    }

    /**
     * Create an instance of {@link BookingsServices }
     * 
     */
    public BookingsServices createBookingsServices() {
        return new BookingsServices();
    }

    /**
     * Create an instance of {@link StatusBooking }
     * 
     */
    public StatusBooking createStatusBooking() {
        return new StatusBooking();
    }

    /**
     * Create an instance of {@link SuccessBooking }
     * 
     */
    public SuccessBooking createSuccessBooking() {
        return new SuccessBooking();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link GuestClient }
     * 
     */
    public GuestClient createGuestClient() {
        return new GuestClient();
    }

    /**
     * Create an instance of {@link Clients }
     * 
     */
    public Clients createClients() {
        return new Clients();
    }

    /**
     * Create an instance of {@link StatusClient }
     * 
     */
    public StatusClient createStatusClient() {
        return new StatusClient();
    }

    /**
     * Create an instance of {@link SuccessClient }
     * 
     */
    public SuccessClient createSuccessClient() {
        return new SuccessClient();
    }

    /**
     * Create an instance of {@link Guest }
     * 
     */
    public Guest createGuest() {
        return new Guest();
    }

    /**
     * Create an instance of {@link Guests }
     * 
     */
    public Guests createGuests() {
        return new Guests();
    }

    /**
     * Create an instance of {@link StatusGuest }
     * 
     */
    public StatusGuest createStatusGuest() {
        return new StatusGuest();
    }

    /**
     * Create an instance of {@link SuccessGuest }
     * 
     */
    public SuccessGuest createSuccessGuest() {
        return new SuccessGuest();
    }

    /**
     * Create an instance of {@link Hotel }
     * 
     */
    public Hotel createHotel() {
        return new Hotel();
    }

    /**
     * Create an instance of {@link Hotels }
     * 
     */
    public Hotels createHotels() {
        return new Hotels();
    }

    /**
     * Create an instance of {@link StatusHotel }
     * 
     */
    public StatusHotel createStatusHotel() {
        return new StatusHotel();
    }

    /**
     * Create an instance of {@link SucessHotel }
     * 
     */
    public SucessHotel createSucessHotel() {
        return new SucessHotel();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link StatusRole }
     * 
     */
    public StatusRole createStatusRole() {
        return new StatusRole();
    }

    /**
     * Create an instance of {@link SuccessRole }
     * 
     */
    public SuccessRole createSuccessRole() {
        return new SuccessRole();
    }

    /**
     * Create an instance of {@link Room }
     * 
     */
    public Room createRoom() {
        return new Room();
    }

    /**
     * Create an instance of {@link Rooms }
     * 
     */
    public Rooms createRooms() {
        return new Rooms();
    }

    /**
     * Create an instance of {@link StatusRoom }
     * 
     */
    public StatusRoom createStatusRoom() {
        return new StatusRoom();
    }

    /**
     * Create an instance of {@link SuccessRoom }
     * 
     */
    public SuccessRoom createSuccessRoom() {
        return new SuccessRoom();
    }

    /**
     * Create an instance of {@link StatusRoomsHotel }
     * 
     */
    public StatusRoomsHotel createStatusRoomsHotel() {
        return new StatusRoomsHotel();
    }

    /**
     * Create an instance of {@link SuccessRoomsHotel }
     * 
     */
    public SuccessRoomsHotel createSuccessRoomsHotel() {
        return new SuccessRoomsHotel();
    }

    /**
     * Create an instance of {@link RoomsHotel }
     * 
     */
    public RoomsHotel createRoomsHotel() {
        return new RoomsHotel();
    }

    /**
     * Create an instance of {@link RoomsHotels }
     * 
     */
    public RoomsHotels createRoomsHotels() {
        return new RoomsHotels();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link StatusService }
     * 
     */
    public StatusService createStatusService() {
        return new StatusService();
    }

    /**
     * Create an instance of {@link SuccessService }
     * 
     */
    public SuccessService createSuccessService() {
        return new SuccessService();
    }

    /**
     * Create an instance of {@link ServiceHotel }
     * 
     */
    public ServiceHotel createServiceHotel() {
        return new ServiceHotel();
    }

    /**
     * Create an instance of {@link ServicesHotels }
     * 
     */
    public ServicesHotels createServicesHotels() {
        return new ServicesHotels();
    }

    /**
     * Create an instance of {@link StatusServiceHotel }
     * 
     */
    public StatusServiceHotel createStatusServiceHotel() {
        return new StatusServiceHotel();
    }

    /**
     * Create an instance of {@link SuccessServiceHotel }
     * 
     */
    public SuccessServiceHotel createSuccessServiceHotel() {
        return new SuccessServiceHotel();
    }

}
