//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.26 at 03:03:09 PM BST 
//


package com.maidenhotels.Backend.tibco.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/TIBCO/Maiden_Hotels_Project/Schemas/RoomsHotel.xsd}SuccessRoomsHotel" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "successRoomsHotel"
})
@XmlRootElement(name = "StatusRoomsHotel", namespace = "http://www.tibco.com/schemas/TIBCO/Maiden_Hotels_Project/Schemas/RoomsHotel.xsd")
public class StatusRoomsHotel {

    @XmlElement(name = "SuccessRoomsHotel", namespace = "http://www.tibco.com/schemas/TIBCO/Maiden_Hotels_Project/Schemas/RoomsHotel.xsd")
    protected SuccessRoomsHotel successRoomsHotel;

    /**
     * Gets the value of the successRoomsHotel property.
     * 
     * @return
     *     possible object is
     *     {@link SuccessRoomsHotel }
     *     
     */
    public SuccessRoomsHotel getSuccessRoomsHotel() {
        return successRoomsHotel;
    }

    /**
     * Sets the value of the successRoomsHotel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuccessRoomsHotel }
     *     
     */
    public void setSuccessRoomsHotel(SuccessRoomsHotel value) {
        this.successRoomsHotel = value;
    }

}
