//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.11 at 09:29:45 AM BST 
//


package com.maidenhotels.Backend.tibco.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/TIBCO/Maiden_Hotels_Project/Schemas/Schema.xsd2}SuccessBackoffice" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "successBackoffice"
})
@XmlRootElement(name = "StatusBackoffice", namespace = "http://www.tibco.com/schemas/TIBCO/Maiden_Hotels_Project/Schemas/Schema.xsd2")
public class StatusBackoffice {

    @XmlElement(name = "SuccessBackoffice", namespace = "http://www.tibco.com/schemas/TIBCO/Maiden_Hotels_Project/Schemas/Schema.xsd2")
    protected SuccessBackoffice successBackoffice;

    public StatusBackoffice() {
    }

    public StatusBackoffice(SuccessBackoffice successBackoffice) {
        this.successBackoffice = successBackoffice;
    }

    /**
     * Gets the value of the successBackoffice property.
     * 
     * @return
     *     possible object is
     *     {@link SuccessBackoffice }
     *     
     */
    public SuccessBackoffice getSuccessBackoffice() {
        return successBackoffice;
    }

    /**
     * Sets the value of the successBackoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuccessBackoffice }
     *     
     */
    public void setSuccessBackoffice(SuccessBackoffice value) {
        this.successBackoffice = value;
    }

}
